### ISSUE TITLE
os-agent_1.4.1_linux_arm64.tar.gz doesn't work

### ISSUE THREAD

**Issue by pric69** [home-assistant/os-agent#110]
Hello,

Please !!! can someone help me ??

Trying to install HA i have an issue i cannot solve since many weeks…(I am new on debian and home assistant)

I have downloaded the file “os-agent_1.4.1_linux_arm64.tar.gz” on my home folder. My Debian in installed on VM with CPU ARM64 (Freebox delta)

I tried this sentence below (being Super User) :
dpkg -i os-agent_1.4.1_linux_arm64.tar.gz

The result is :
error : ‘os-agent_1.4.1_linux_arm64.tar.gz’ is not a Debian format archive. dpkg-deb --control subprocess returned error exit status 2

So I have unzipped the .tar.gz file to ectract 3 files : "Readme.md" / "LICENC"E and "os-agent"...So I tried "dpkg -i os-agent" without success
What shall I do with these files ????

Thanks in advance to help me

Best regards

Patrick

**Comment by agners** [comment]
For Debian, just use `os-agent_1.4.1_linux_aarch64.deb`.

**Comment by pric69** [comment]
Hi Agners,

I tried this command to install HA :  "dpkg -i os-agent_1.4.1_linux_aarch64.deb"

But it still NOT OK

![image](https://user-images.githubusercontent.com/43902868/201741527-7a777f79-4fb0-4a51-a987-cebe588bf240.png)

Best regards

Patrick

**Comment by frenck** [comment]
This is an issue with your system setup, for example, `start-stop-daemon` is part of the `dpkg` in Debian (which you have, since you are invoking the command in the above example).

It looks like your `PATH` isn't correct (as per warning/note `dpkg` is issuing).

Closing the issue on this end, since it is an environment issue and not an issue with the package provided.

../Frenck
