### ISSUE TITLE
How do I uninstall OS Agent?

### ISSUE THREAD

**Issue by ivanovd** [home-assistant/os-agent#57]
I have issues with the network routings and the host system doesn't resolve any addresses after installing OS Agent on raspbian bulsseye. How do I uninstall OS Agent?

**Comment by agners** [comment]
As this is a regular Debian package, just like any other Debian package: use `dpkg -r os-agent`. I'll extend the `README.md`.

**Comment by cociweb** [comment]
Hello unfortunatelly, it is not true in case of ubuntu latest lts.
since the the supervised installer (https://github.com/home-assistant/supervised-installer) requires os-agent, you are not able to remove os-agent. (or you need to remove home-assistant as well).
If you decide to remove the os-agent without the dependant package (`dpkg -r --force-depends os-agent`) you will broke your apt package handler:
![image](https://user-images.githubusercontent.com/1935413/148205764-2c347a3e-5371-496c-a73c-7595ff8de0a0.png)

**Comment by frenck** [comment]
>  ubuntu latest lts.

Ubuntu isn't a supported system.

**Comment by cociweb** [comment]
Yes, I know, but it's working on it without os-agent. :)
For a future Me here is the workaround: you can edit the `/var/lib/dpkg/status` file on ubuntu and remove the os-agent dependency and make it as a suggests. - and now you are able to remove on ubuntu as well.
Maybe it could be an official solution in the installer.

**Comment by frenck** [comment]
> Yes, I know, but it's working on it without os-agent. :)

That isn't supported either. If you want to discuss unsupported installation methods, please use our community forum.
